# Generated by Django 4.1.5 on 2023-05-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('kdjual', models.CharField(default='J001', max_length=4, primary_key=True, serialize=False)),
                ('kdbrg', models.CharField(max_length=4)),
                ('nmbrg', models.CharField(max_length=100)),
                ('tgltrans', models.DateField()),
                ('jumbrg', models.IntegerField()),
                ('hargabrg', models.FloatField()),
                ('totalbyr', models.FloatField()),
            ],
        ),
    ]
