# Generated by Django 4.1.5 on 2023-05-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='tgltrans',
            field=models.DateTimeField(),
        ),
    ]
